// <auto-generated />
namespace medical_care.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class initialPolicyRequest : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initialPolicyRequest));
        
        string IMigrationMetadata.Id
        {
            get { return "202003140743590_initialPolicyRequest"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
