// <auto-generated />
namespace medical_care.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updateEmp : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateEmp));
        
        string IMigrationMetadata.Id
        {
            get { return "202003161743246_updateEmp"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
